### ISSUE TITLE
Remove API keys from source

### ISSUE THREAD

**Issue by amalbansode** [sidpagariya/better-maps#2]
I think the current state might be problematic since the API is rate-limited, and if someone were to use your exposed keys (for whatever intents and purposes, I don't know), it might hamper this app's functioning. Perhaps create a separate `config.json` where users who wish to build from source can specify their own API key? 

In general though, I'm not sure what the solution for this is. Removing keys from GitHub is a tiny fix. Even once this app is published somewhere, your API key will be exposed since there's no backend through which requests are routed. I imagine this is a recurring problem for any front-end javascript app. I don't know how it's supposed to be solved.

**Comment by sidpagariya** [comment]
Hi @amalbansode this is a temporary throw-away key and I will update the project source accordingly as soon as the permanent key is in place so that secrets are not public!
